### ISSUE TITLE
Features (discussion)

### ISSUE THREAD

**Issue by jbinda** [IvanFon/super-labeler-action#3]
Hey since you have merge my PR I decided to open an issue to move conversation about features here.

According to [this comment](https://github.com/IvanFon/super-labeler-action/pull/1#issuecomment-605803043) there is already some ideas:

- [ ] checking the PR size (count deletiion/addition similar to `codelytv/pr-size-labeler@v1`
action ) (see #12)
- [ ] be able to pass fallback if the is no match for label when opening PR/issue (default label can be `need_triage` or something like that - my teammate @jayu came up with this idea when I show him your repo)(see #13 )
- [ ] unit tests/automated testing (in progress, mentioned above) (see #8)
- [ ] an option to delete any labels that exist on the repository but aren't in your labels.json
this is potentially destructive, so it would definitely be off by default, but I think it could be useful
I'm currently working on a web-based UI for generating configurations in the web branch
it's far from done, but if you want to see the progress so far, you can look at: https://ivanfon.github.io/super-labeler-action/ (see #4)
- [ ] condition for pr's that still need approval (see #6)
- [ ] some way to specify more advanced combinations of condition for example, if branchMatches and titleMatches, etc (see #7)
- [ ] a better documentation system, updating the README will get tedious soon (see #9)

I will also extend the list with below:

- [ ] task which fails to prevent merging (I'm using [wip app](https://github.com/apps/wip) right now but also saw some action and it allow to have all in one place) (see #11)
- [ ] be able to test, run debug action locally (see #10)

Feel free to edit if something is wrong here

**Comment by IvanFon** [comment]
Thanks for summarizing here! I think separate issues will be easier to deal with. I added issues for things I have planned, please feel free to add issues for features you want and close this issue.

**Comment by IvanFon** [comment]
Thank you! Closing for discussion on individual issues.
